[package]
name = "adevice_proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/mod.rs"

[dependencies]
protobuf = { version = "3.2.0", path = "../../../../external/rust/crates/protobuf" }
